// export const FETCH_LIST_DEMANDE_CHEQUIER_REQUEST =
//   "FETCH_LIST_DEMANDE_CHEQUIER_REQUEST";
// export const FETCH_LIST_DEMANDE_CHEQUIER_SUCCESS =
//   "FETCH_LIST_DEMANDE_CHEQUIER_SUCCESS";
// export const FETCH_LIST_DEMANDE_CHEQUIER_FAILURE =
//   "FETCH_LIST_DEMANDE_CHEQUIER_FAILURE";

// export const FETCH_DEMANDE_CHEQUIER_REQUEST = "FETCH_DEMANDE_CHEQUIER_REQUEST";
// export const SAVE_DEMANDE_CHEQUIER_REQUEST = "SAVE_DEMANDE_CHEQUIER_REQUEST";
// export const UPDATE_DEMANDE_CHEQUIER_REQUEST =
//   "UPDATE_DEMANDE_CHEQUIER_REQUEST";
// export const SIGN_DEMANDE_CHEQUIER_REQUEST = "SIGN_DEMANDE_CHEQUIER_REQUEST";

// export const DEMANDE_CHEQUIER_SUCCESS = "DEMANDE_CHEQUIER_SUCCESS";
// export const DEMANDE_CHEQUIER_FAILURE = "DEMANDE_CHEQUIER_FAILURE";
